######################################################################
##
## Filename: tb_dataGenConsume.udo
## Created on: Tue Feb 14 14:49:45 GMT Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
