C:\Modeltech_pe_edu_10.4a\win32pe_edu/vlib "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/secureip"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vmap secureip "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/secureip"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vlib "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/unimacro"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vmap unimacro "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/unimacro"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vlib "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/unisim"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vmap unisim "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/unisim"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vlib "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/simprim"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vmap simprim "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/simprim"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vlib "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/xilinxcorelib"
C:\Modeltech_pe_edu_10.4a\win32pe_edu/vmap xilinxcorelib "C:\Users\Naimul Hoque\Documents\Uni Work\Year 2\Digital Design\Assignment 2\UART\Digital-Design-Assignment-2\fullSystem\FULL_SYSTEM/xilinxcorelib"
